volumes:
  data_zk: { }
  data_bk: { }
  data_kf1: { }
  data_kf2: { }
  data_kf3: { }

services:
  # Start zookeeper
  zookeeper:
    image: apachepulsar/pulsar:4.0.2
    container_name: zookeeper
    restart: on-failure
    user: root
    ports:
      - "2181:2181"
    volumes:
      - data_zk:/pulsar/data/zookeeper
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
             bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
             exec bin/pulsar zookeeper"
    healthcheck:
      test: [ "CMD", "bin/pulsar-zookeeper-ruok.sh" ]
      interval: 10s
      timeout: 5s
      retries: 30

  # Init cluster metadata
  pulsar-init:
    container_name: pulsar-init
    hostname: pulsar-init
    image: apachepulsar/pulsar:4.0.2
    command: >
      bash -c "bin/pulsar initialize-cluster-metadata --cluster kuze --zookeeper zookeeper:2181 --configuration-store zookeeper:2181 --web-service-url http://broker:8080 --broker-service-url pulsar://broker:6650"
    depends_on:
      zookeeper:
        condition: service_healthy

  # Start bookie
  bookie:
    image: apachepulsar/pulsar:4.0.2
    container_name: bookie
    user: root
    restart: on-failure
    environment:
      - clusterName=kuze
      - zkServers=zookeeper:2181
      - metadataServiceUri=metadata-store:zk:zookeeper:2181
      - advertisedAddress=bookie
      - BOOKIE_MEM=-Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=1024m
    depends_on:
      zookeeper:
        condition: service_healthy
      pulsar-init:
        condition: service_completed_successfully
    volumes:
      - data_bk:/pulsar/data/bookkeeper
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"

  # Start broker
  broker:
    image: apachepulsar/pulsar:4.0.2
    container_name: broker
    hostname: broker
    restart: on-failure
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - zookeeperServers=zookeeper:2181
      - clusterName=kuze
      - managedLedgerDefaultEnsembleSize=1
      - managedLedgerDefaultWriteQuorum=1
      - managedLedgerDefaultAckQuorum=1
      - allowAutoTopicCreation=true
      - allowAutoTopicCreationType=partitioned
      - defaultNumPartitions=9
      - brokerDeleteInactiveTopicsEnabled=false
      - brokerDeduplicationEnabled=true
      - transactionCoordinatorEnabled=true
      - advertisedAddress=broker
      - advertisedListeners=external:pulsar://localhost:6650
      - PULSAR_MEM=-Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=512m
    depends_on:
      zookeeper:
        condition: service_healthy
      bookie:
        condition: service_started
    command: bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"

  pulsar-init-transaction:
    container_name: pulsar-init-transaction
    hostname: pulsar-init-transaction
    image: apachepulsar/pulsar:4.0.2
    command: >
      bash -c "bin/pulsar initialize-transaction-coordinator-metadata -cs zookeeper:2181 -c kuze"
    depends_on:
      broker:
        condition: service_started

  kafka1:
    image: bitnami/kafka:3.3.2
    container_name: kafka1
    hostname: kafka1
    user: root
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=INTERNAL
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,INTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,PLAINTEXT://localhost:9092
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_BROKER_ID=1
    volumes:
      - data_kf1:/bitnami/kafka

