apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume 
spec:
  volumes:
    - name: configmap-volume
      configMap:
        name: my-configmap-java
        items:
          - key: config.properties   # 来源 key
            path: config.properties  # 映射后的文件名
  containers:
  - name: test-configmap-volume
    image: busybox
    command: 
    - sleep
    - '86400'
    volumeMounts:
    - name: configmap-volume
      mountPath: "/projected-volume"
      readOnly: true
  