apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mynamespace
  name: example-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  #resourcenames: ["example-pod"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]