apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume 
spec:
  volumes:
    - name: mysql-cred
      secret:
        secretName: my-secret-mysql
        items:
          - key: user
            path: username
          - key: pass
            path: password
  containers:
  - name: test-secret-volume
    image: busybox
    command: 
    - sleep
    - '86400'
    volumeMounts:
    - name: mysql-cred
      mountPath: "/projected-volume"
      readOnly: true
  